// Code generated by "stringer -type=Label"; DO NOT EDIT.

package boilerpipe

import "strconv"

const _Label_name = "LabelIndicatesEndOfTextLabelMightBeContentLabelVeryLikelyContentLabelTitleLabelListLabelHeadingLabelHeading1LabelHeading2LabelHeading3"

var _Label_index = [...]uint8{0, 23, 42, 64, 74, 83, 95, 108, 121, 134}

func (i Label) String() string {
	if i < 0 || i >= Label(len(_Label_index)-1) {
		return "Label(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Label_name[_Label_index[i]:_Label_index[i+1]]
}
